package com.placelook.util;

/**
 * Created by victor on 29.10.17.
 */

public enum NetworkType {
    PREF_NET_TYPE_GSM_WCDMA,/* GSM/WCDMA (WCDMA preferred) */
    PREF_NET_TYPE_GSM_ONLY, /* GSM only */
    PREF_NET_TYPE_WCDMA, /* WCDMA  */
    PREF_NET_TYPE_GSM_WCDMA_AUTO, /* GSM/WCDMA (auto mode, according to PRL) */
    PREF_NET_TYPE_CDMA_EVDO_AUTO, /* CDMA and EvDo (auto mode, according to PRL) */
    PREF_NET_TYPE_CDMA_ONLY, /* CDMA only */
    PREF_NET_TYPE_EVDO_ONLY, /* EvDo only */
    PREF_NET_TYPE_GSM_WCDMA_CDMA_EVDO_AUTO, /* GSM/WCDMA, CDMA, and EvDo (auto mode, according to PRL) */
    PREF_NET_TYPE_LTE_CDMA_EVDO, /* LTE, CDMA and EvDo */
    PREF_NET_TYPE_LTE_GSM_WCDMA, /* LTE, GSM/WCDMA */
    PREF_NET_TYPE_LTE_CMDA_EVDO_GSM_WCDMA, /* LTE, CDMA, EvDo, GSM/WCDMA */
    PREF_NET_TYPE_LTE_ONLY, /* LTE only */
    PREF_NET_TYPE_LTE_WCDMA,  /* LTE/WCDMA */
    PREF_NET_TYPE_TD_SCDMA_ONLY, /* TD-SCDMA only */
    PREF_NET_TYPE_TD_SCDMA_WCDMA, /* TD-SCDMA and WCDMA */
    PREF_NET_TYPE_TD_SCDMA_LTE, /* TD-SCDMA and LTE */
    PREF_NET_TYPE_TD_SCDMA_GSM, /* TD-SCDMA and GSM */
    PREF_NET_TYPE_TD_SCDMA_GSM_LTE, /* TD-SCDMA,GSM and LTE */
    PREF_NET_TYPE_TD_SCDMA_GSM_WCDMA, /* TD-SCDMA, GSM/WCDMA */
    PREF_NET_TYPE_TD_SCDMA_WCDMA_LTE, /* TD-SCDMA, WCDMA and LTE */
    PREF_NET_TYPE_TD_SCDMA_GSM_WCDMA_LTE, /* TD-SCDMA, GSM/WCDMA and LTE */
    PREF_NET_TYPE_TD_SCDMA_GSM_WCDMA_CDMA_EVDO_AUTO, /* TD-SCDMA, GSM/WCDMA, CDMA and EvDo */
    PREF_NET_TYPE_TD_SCDMA_LTE_CDMA_EVDO_GSM_WCDMA, /* TD-SCDMA, LTE, CDMA, EvDo GSM/WCDMA */
    PREF_WIFI, /*  WIFI */
    PREF_MOBILE, /* ALL IN UP WITHOUT WIFI */
    PREF_NONETWORK
}
